package com.example.demo;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.dao.DataIntegrityViolationException;
import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
class MigrationTests {
    @Autowired Flyway flyway;
    @Autowired JdbcTemplate jdbc;
    @Autowired javax.sql.DataSource dataSource;

    @Test void upgradesV2WithExistingOrdersAndEnforcesProjectIntegrity() throws Exception {
        String schema = "upgrade_" + java.util.UUID.randomUUID().toString().replace("-", "");
        String quotedSchema = "\"" + schema + "\"";
        try {
            Flyway.configure().dataSource(dataSource).schemas(schema).defaultSchema(schema).target("2").load().migrate();
            jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin, description, priority) VALUES ('MANUAL', 'Legacy manual', 'ALTA')");
            jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin, description, priority) VALUES ('INSPECCION', 'Legacy inspection', 'MEDIA')");
            var upgrade = Flyway.configure().dataSource(dataSource).schemas(schema).defaultSchema(schema).load();
            assertEquals(2, upgrade.migrate().migrationsExecuted);
            assertEquals(2L, jdbc.queryForObject("SELECT COUNT(*) FROM " + quotedSchema + ".orden_trabajo WHERE project_id IS NULL", Long.class));
            assertEquals(1L, jdbc.queryForObject("SELECT COUNT(*) FROM " + quotedSchema + ".orden_trabajo WHERE origin='MANUAL' AND description='Legacy manual'", Long.class));
            jdbc.update("INSERT INTO " + quotedSchema + ".proyecto_obra(id,name,estimated_budget,estimated_start_date,estimated_duration_days) VALUES (100,'Project migration',1000,CURRENT_DATE,30)");
            jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin,description,priority,project_id) VALUES ('PROYECTO','Linked','ALTA',100)");
            assertThrows(DataIntegrityViolationException.class, () -> jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin,description,priority,project_id) VALUES ('PROYECTO','Missing','ALTA',999999)"));
            assertThrows(DataIntegrityViolationException.class, () -> jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin,description,priority) VALUES ('PROYECTO','No project','ALTA')"));
            assertThrows(DataIntegrityViolationException.class, () -> jdbc.update("INSERT INTO " + quotedSchema + ".orden_trabajo(origin,description,priority,project_id) VALUES ('MANUAL','Unexpected project','ALTA',100)"));
            assertThrows(DataIntegrityViolationException.class, () -> jdbc.update("DELETE FROM " + quotedSchema + ".proyecto_obra WHERE id=100"));
            upgrade.validate();
            assertEquals(0, upgrade.migrate().migrationsExecuted);
        } finally {
            // Only the isolated schema generated by this test is removed.
            jdbc.execute("DROP SCHEMA IF EXISTS " + quotedSchema + " CASCADE");
        }
    }

    @Test void latestMigrationIsAppliedAndPreservesData() {
        assertEquals("4", flyway.info().current().getVersion().toString());
        jdbc.update("INSERT INTO material(nombre, unidad) VALUES (?, ?)", "Migration preservation fixture", "kg");
        var count = jdbc.queryForObject("SELECT COUNT(*) FROM material", Long.class);
        flyway.validate();
        assertEquals(0, flyway.migrate().migrationsExecuted);
        assertEquals(count, jdbc.queryForObject("SELECT COUNT(*) FROM material", Long.class));
    }

    @Test void schemaEnforcesRelationsAndRequiredColumns() {
        assertThrows(DataIntegrityViolationException.class, () -> jdbc.update(
                "INSERT INTO evidencia(orden_trabajo_id, storage_reference, fecha) VALUES (999999999, 'test', CURRENT_TIMESTAMP)"));
        assertThrows(DataIntegrityViolationException.class, () -> jdbc.update("INSERT INTO cuadrilla(nombre) VALUES (NULL)"));
    }
}
