-- Initial schema. Applied once by Flyway; Hibernate only validates mappings.
-- Compatible with PostgreSQL and H2 PostgreSQL mode for the fast test suite.
CREATE TABLE cuadrilla (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE material (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL,
    unidad VARCHAR(30)
);

CREATE TABLE maquinaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL
);

CREATE TABLE proyecto_obra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    scope VARCHAR(1000),
    location VARCHAR(300),
    estimated_budget NUMERIC(15,2) NOT NULL,
    approved_budget NUMERIC(15,2),
    used_budget NUMERIC(15,2) NOT NULL DEFAULT 0,
    estimated_start_date DATE NOT NULL,
    estimated_duration_days INTEGER NOT NULL,
    approved_deadline_days INTEGER,
    physical_progress INTEGER NOT NULL DEFAULT 0,
    approval_status VARCHAR(30) NOT NULL DEFAULT 'BORRADOR'
        CHECK (approval_status IN ('BORRADOR','PENDIENTE_APROBACION','APROBADO','RECHAZADO')),
    activity_status VARCHAR(30)
        CHECK (activity_status IN ('SIN_INICIAR','EN_EJECUCION','PAUSADA','FINALIZADA')),
    technical_manager VARCHAR(200),
    contractor VARCHAR(200)
);

CREATE TABLE orden_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_request_id VARCHAR(100),
    origin VARCHAR(30) NOT NULL CHECK (origin IN ('MANUAL','ATENCION_CIUDADANA','INSPECCION')),
    description VARCHAR(1000) NOT NULL,
    intervention_type VARCHAR(100),
    location VARCHAR(300),
    priority VARCHAR(20) NOT NULL CHECK (priority IN ('BAJA','MEDIA','ALTA')),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (status IN ('PENDIENTE','PROGRAMADA','ASIGNADA','EN_EJECUCION','PAUSADA','COMPLETADA','VALIDADA','REABIERTA')),
    cuadrilla_id BIGINT REFERENCES cuadrilla(id),
    scheduled_date DATE,
    estimated_duration_hours INTEGER,
    outcome VARCHAR(1000)
);

CREATE TABLE evidencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT NOT NULL REFERENCES orden_trabajo(id),
    storage_reference VARCHAR(500) NOT NULL,
    descripcion VARCHAR(500),
    fecha TIMESTAMP(6) NOT NULL
);

CREATE TABLE observacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT NOT NULL REFERENCES orden_trabajo(id),
    texto VARCHAR(1000) NOT NULL,
    fecha TIMESTAMP(6) NOT NULL
);

CREATE TABLE material_asignado (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT NOT NULL REFERENCES orden_trabajo(id),
    material_id BIGINT NOT NULL REFERENCES material(id),
    cantidad_requerida NUMERIC(12,2) NOT NULL,
    cantidad_consumida NUMERIC(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE maquinaria_asignada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orden_trabajo_id BIGINT NOT NULL REFERENCES orden_trabajo(id),
    maquinaria_id BIGINT NOT NULL REFERENCES maquinaria(id),
    horas_asignadas INTEGER NOT NULL
);

CREATE TABLE street_closure (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    closure_request_id VARCHAR(255) NOT NULL UNIQUE,
    work_order_id BIGINT NOT NULL REFERENCES orden_trabajo(id),
    location VARCHAR(300) NOT NULL,
    requested_from DATE NOT NULL,
    requested_to DATE NOT NULL,
    reason VARCHAR(1000) NOT NULL,
    status VARCHAR(255) NOT NULL
);

CREATE TABLE street_closure_affected_sections (
    street_closure_id BIGINT NOT NULL REFERENCES street_closure(id),
    section_order INTEGER NOT NULL,
    affected_sections VARCHAR(300) NOT NULL,
    PRIMARY KEY (street_closure_id, section_order)
);

CREATE INDEX idx_orden_trabajo_cuadrilla ON orden_trabajo(cuadrilla_id);
CREATE INDEX idx_evidencia_orden ON evidencia(orden_trabajo_id);
CREATE INDEX idx_observacion_orden ON observacion(orden_trabajo_id);
CREATE INDEX idx_material_asignado_orden ON material_asignado(orden_trabajo_id);
CREATE INDEX idx_material_asignado_material ON material_asignado(material_id);
CREATE INDEX idx_maquinaria_asignada_orden ON maquinaria_asignada(orden_trabajo_id);
CREATE INDEX idx_maquinaria_asignada_maquinaria ON maquinaria_asignada(maquinaria_id);
CREATE INDEX idx_street_closure_orden ON street_closure(work_order_id);
