-- No credentials or demo users are included in versioned migrations.
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(30) NOT NULL CHECK (role IN ('PERSONAL_OBRAS','RESPONSABLE_AUTORIZADO',
        'JEFE_CUADRILLA','OPERARIO_CONTRATISTA','INSPECTOR_OBRA','INGENIERO_ARQUITECTO')),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    token_version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_app_user_canonical_username CHECK (username = LOWER(TRIM(username)))
);
